export default {
    zh: {
        all_products: '所有商品',
        buy: '购买',
        whitepaper: '白皮书',
        about: '关于',
        profile: '个人主页',
        log_out: '登出',
        buy_now: '现在购买',
        counting_down: '正式开售时间 北京时间上午11点 2021年1月1日',
        introduction: '功能介绍',
        roadmap: '路线图',
        pre_sale: '预购',
        official_sale: '正式发售',
        matrix_banner_title:'Matrix World是Phanta Bear NFT的技术合作伙伴',
        matrix_banner_content:'Matrix是一个可编程的3D多链元宇宙。这个世界包含以NFT形式存在的土地，这些土地将在以太坊和FLOW链上永久存在。点击这里查看更多.(link)',
        team: '团队',
        collaborator: '合作方',
        outline: '目录',
        faq: '常见问题',
        more: '更多',
        links: '链接',
        opensea: 'opensea'
    },
    en: {
        all_products: 'all products',
        buy: 'buy',
        whitepaper: 'whitepaper',
        about: 'about',
        profile: 'profile',
        log_out: 'log out',
        buy_now: 'BUY NOW',
        counting_down: 'The NFT initial sale starts on 11:00 AM CST Jan. 1st 2022',
        introduction: 'INTRODUCTION',
        roadmap: 'ROADMAP',
        pre_sale: 'PRE-SALE',
        official_sale: ' OFFICAL-SALE',
        matrix_banner_title:'Matrix World is the technical partner of Phanta Bear NFT',
        matrix_banner_content:'Matrix is a Programmable 3D Multichain Metaverse. The world consists of Lands, issued as Non-Fungible Tokens (NFTs), which permanently persist on blockchain networks including Ethereum and Flow.See more here.(link)',
        team: 'TEAM',
        collaborator: 'COLLABORATOR',
        outline: 'OUTLINE',
        faq: 'FAQ',
        more: 'MORE',
        links: 'LINKS',
        opensea: 'opensea'
    }
  };
