export default {
    zh: {
        homepage: '主页',
        sign_in: '登陆',
        all_products: 'NFT',
        buy: '购买',
        team: '团队',
        roadmap: '路线图',
        whitepaper: '白皮书',
        about: '关于',
        profile: '个人主页',
        log_out: '登出',
        buy_now: '现在购买',
        counting_down1: '正式开售时间',
        counting_down2: '上午11点 2022年1月1日 UTC+8',
        introduction: '功能介绍',
        introduction_title1: 'Phanta Bear',
        introduction_content1: '每只Phanta Bear都是独一无二的，都会解锁不同的访问和特权级别。',
        introduction_title2: 'Metaverse',
        introduction_content2: 'Phanta Bear NFT拥有者将提前体验Ezek Metaverse新娱乐世界。',
        introduction_title3: 'Jay同款',
        introduction_content3: '每只Phanta Bear的服装和配饰都是由周杰伦和Ric的时尚品牌PHANTACi设计。',
        introduction_title4: '会员权益',
        introduction_content4: '您的 Phanta Bear 兼作您的 Ezek 会员卡，并享受会员专享权益。',
        roadmap_time1: '2022',
        roadmap_time1_1: '01/01',
        roadmap_content1: 'Ezek.io 平台 and Phanta Bear NFT 正式发售， Ezek 俱乐部社区正式推出，并提供特别权益。',
        roadmap_time2: '2022',
        roadmap_time2_1: 'Q1',
        roadmap_content2: '社区将投票选出 4 只 Phanta Bear，它们包含在PHANTACi Spring 2022 推出的实物收藏中。 Ezek将推出另一个巨星的 NFT ，并发布Ezek Club 线上/线下福利，同时开始搭建 Ezek 虚拟演唱会。',
        roadmap_time3: '2022',
        roadmap_time3_1: 'Q2',
        roadmap_content3: 'Ezek 虚拟演唱会启动。 Ezek将购买一块虚拟土地并在 Metaverse 中建造一个仅限会员参与的会所，与演唱会和电影制片厂团队合作完成。',
        roadmap_time4: '2022',
        roadmap_time4_1: 'Q3',
        roadmap_content4: '您将能够使用 Ezek NFT 参与虚拟演唱会。',
        matrix_banner_title: 'Matrix Labs 是 Ezek 的技术合作伙伴',
        matrix_banner_content1: 'Matrix Labs 由一群经验丰富的区块链开发人员组成。他们与 Ezek 合作，将 Phanta Bear NFT Collection 带到区块链的世界中。',
        matrix_banner_content2: 'Matrix Labs 同时也是 Matrix World 背后的创造者，这是一个振奋人心的新时代元宇宙项目。在 Matrix World 中，用户可以用一个全新的方式创建、连接、探索和游戏。他们甚至可以通过出售他们的作品来收益！',
        matrix_banner_content3: '点击',
        matrix_banner_content4: '这里',
        matrix_banner_content5: '查看更多。',
        team_1: 'WILL L',
        team_1_introduction: 'Will L 是一个肌肉男，他为中国流行天王写了许多著名的歌词。现在他将把传统的娱乐世界带到新的区块链世界！',
        team_2: 'Mark G',
        team_2_introduction: '他在巴黎学习电影制作多年，并曾与一位好莱坞传奇明星一起周游世界，将中国文化带给了中东和西方的各路名流。现在他想把他所有的娱乐体验带到这个新的区块链世界。',
        team_3: 'Ed Ow',
        team_3_introduction: '技术联合创始人 Ed Ow，曾与 HTC 等合作。Ed Ow 是一位连续创业者和投资者，以其创造性思维而闻名。他曾在加州大学伯克利分校学习能源经济学期间创立、管理或出售了几家成功的企业。',
        collaborator: '合作方',
        outline: '目录',
        faq: '常见问题',
        disclaimer: '免责声明',
        more: '更多',
        links: '链接',
        all_rights_reserved1: 'All rights reserved by Starvision Entertainment Ltd.',
        all_rights_reserved2: '© 2022 Starvision Entertainment Ltd.',
        opensea: 'opensea'
    },
    en: {
        homepage: 'Homepage',
        sign_in: 'SIGN IN',
        all_products: 'NFT',
        buy: 'Buy',
        team: 'Team',
        roadmap: 'Roadmap',
        whitepaper: 'Whitepaper',
        about: 'About',
        profile: 'Profile',
        log_out: 'Log Out',
        buy_now: 'BUY NOW',
        counting_down1: 'The Phanta Bear sale starts at',
        counting_down2: '11:00 AM Jan. 1st 2022 UTC+8',
        introduction: 'INTRODUCTION',
        introduction_title1: 'Phanta Bear',
        introduction_content1: 'Each Phanta Bear has a unique set of traits and unlocks varying, unique levels of access and perks for its owner.',
        introduction_title2: 'Metaverse',
        introduction_content2: 'Phanta Bear NFT owners will experience the new entertainment world of Ezek Metaverse in advance.',
        introduction_title3: 'JAY style',
        introduction_content3: 'Every Phanta Bear features clothing and accesories designed by PHANTACi, the fashion brand co-founded by Jay Chou and his friend Ric in 2006.',
        introduction_title4: 'Membership',
        introduction_content4: 'Your Phanta Bear doubles as your Fantasy membership card, and grants you access to members-only benefits.',
        roadmap_time1: '2022',
        roadmap_time1_1: '01/01',
        roadmap_content1: 'Ezek.io platform and Phanta Bear NFT release and Ezek Club Community launch with special benefits.',
        roadmap_time2: '2022',
        roadmap_time2_1: 'Q1',
        roadmap_content2: 'Community vote for 4 Phanta Bears from the digital NFT collection to be included in the physical upcoming Phantaci Spring 2022 collection. Another top celebrity NFT launch, Ezek Club online/offline benefits start to launch. Ezek virtual concert start to build.',
        roadmap_time3: '2022',
        roadmap_time3_1: 'Q2',
        roadmap_content3: 'Ezek Virtual Concert Launch. Buy a plot of virtual land and build a members-only clubhouse in the Metaverse. Collaborate with concerts and film studios. ',
        roadmap_time4: '2022',
        roadmap_time4_1: 'Q3',
        roadmap_content4: 'You will be able to use Ezek NFT to access to virtual concert.',
        matrix_banner_title: 'Matrix Labs is the technical partner of Ezek',
        matrix_banner_content1: 'The Matrix Labs team is a group of experienced blockchain developers. They are partnering with Ezek to bring the Phanta Bear NFT Collection to life on the blockchain.',
        matrix_banner_content2: 'Matrix Labs are also the creators behind Matrix World, an exciting next-generation metaverse project. In the Matrix World, users will be able to create, connect, explore, and play like never before; they will even be able to earn by selling their creations!',
        matrix_banner_content3: ' See more ',
        matrix_banner_content4: ' here',
        matrix_banner_content5: '.',
        team_1: 'WILL L',
        team_1_introduction: 'Will L is a Muscle Man, who has wrote famous Lyric for the Mandopop King. Now he will bring the traditional entertainment world to the New Blockchain World!',
        team_2: 'Mark G',
        team_2_introduction: 'He has Studied filmmaking in Paris for years and he has traveled all over the world with a legendary star from Hollywood. Bringing the Chinese culture to the top people to Mid-East and West. Now he wants to bring all his entertainment experience to this New Blockchain World.',
        team_3: 'Ed Ow',
        team_3_introduction: 'Ed Ow, the technical co-founder, has worked with partners such as HTC.Ed Ow is a serial entrepreneur and investor well-known for his out-of-the-box thinking. He founded, managed, or sold several successful businesses while studying Energy Economics at UC Berkeley.',
        collaborator: 'COLLABORATOR',
        outline: 'OUTLINE',
        faq: 'FAQ',
        disclaimer: 'Disclaimer',
        more: 'MORE',
        links: 'LINKS',
        all_rights_reserved1: 'All rights reserved by Starvision Entertainment Ltd.',
        all_rights_reserved2: '© 2022 Starvision Entertainment Ltd.',
        opensea: 'opensea'
    }
  };
