export default {
    zh: {
        homepage: '主页',
        all_products: '所有商品',
        buy: '购买',
        whitepaper: '白皮书',
        about: '关于',
        profile: '个人主页',
        log_out: '登出',
        buy_now: '现在购买',
        counting_down1: '正式开售时间',
        counting_down2: '北京时间上午11点 2022年1月1日',
        introduction: '功能介绍',
        introduction_title1: 'Phanta Bear',
        introduction_content1: '每只Phanta Bear都是独一无二的，都会解锁不同的访问和特权级别。',
        introduction_title2: 'Arweave',
        introduction_content2: 'Arweave 的出现带来了一个完美的存储解决方案。通过独特的共识机制来保证数据的永久存储。',
        introduction_title3: '杰伦同款',
        introduction_content3: '每只Phanta Bear的服装和配饰都是由周杰伦和Ric的时尚品牌PHANTACi设计',
        introduction_title4: '会员权益',
        introduction_content4: '您的 Phanta Bear 兼作您的 Ezek 会员卡，并享受会员专享权益。',
        roadmap: '路线图',
        roadmap_time1: '2022',
        roadmap_time1_1: '01/01',
        roadmap_content1: 'Ezek.io 平台 and Phanta Bear NFT 正式发售， Ezek 俱乐部社区正式推出，并提供特别权益',
        roadmap_time2: '2022',
        roadmap_time2_1: 'Q1',
        roadmap_content2: '社区将投票选出 4 只 Phanta Bear，它们包含在Phantaci Spring 2022 推出的实物收藏中。 将推出另一个巨星的 NFT ，Ezek Club 线上/线下福利开始发布。 Ezek 虚拟音乐会开始建设。',
        roadmap_time3: '2022',
        roadmap_time3_1: 'Q2',
        roadmap_content3: 'Ezek 虚拟音乐会启动。 将购买一块虚拟土地并在 Metaverse 中建造一个仅限会员参与的会所。 将与音乐会和电影制片厂合作。',
        roadmap_time4: '2022',
        roadmap_time4_1: 'Q3',
        roadmap_content4: '您将能够使用 Ezek NFT 参与虚拟音乐会。',
        pre_sale: '预购',
        official_sale: '正式发售',
        matrix_banner_title: 'Matrix Labs是Phanta Bear NFT的技术合作伙伴',
        matrix_banner_content1: 'Matrix Labs 由一群经验丰富的区块链开发人员组成。他们与 Ezek 和 PHANTACi 合作，将 Phanta Bear NFT Collection 带到区块链的世界中。',
        matrix_banner_content2: 'Matrix Labs 同时也是 Matrix World 背后的创造者，这是一个振奋人心的新时代元宇宙项目。在 Matrix World 中，用户可以用一个全新的方式创建、连接、探索和游戏。他们甚至可以通过出售他们的作品来收益！',
        matrix_banner_content3: '点击',
        matrix_banner_content4: '这里',
        matrix_banner_content5: '查看更多。',
        team: '团队',
        team_1: 'WILL L',
        team_2: 'Mark G',
        team_3: 'Ed Ow',
        collaborator: '合作方',
        outline: '目录',
        faq: '常见问题',
        more: '更多',
        links: '链接',
        opensea: 'opensea'
    },
    en: {
        homepage: 'homepage',
        all_products: 'all products',
        buy: 'buy',
        whitepaper: 'whitepaper',
        about: 'about',
        profile: 'profile',
        log_out: 'log out',
        buy_now: 'BUY NOW',
        counting_down1: 'The NFT initial sale starts on ',
        counting_down2: '11:00 AM CST Jan. 1st 2022',
        introduction: 'INTRODUCTION',
        introduction_title1: 'Phanta Bear',
        introduction_content1: 'Each Phanta Bear has unique traits, and each PHB unlocks varying and unique levels of access and Perks. ',
        introduction_title2: 'Arweave',
        introduction_content2: 'The emergence of Arweave has brought a perfect storage solution. Through a unique consensus mechanism to ensure the permanent storage of data.',
        introduction_title3: 'JAY style',
        introduction_content3: 'Every Phanta Bear features clothing and accessories designed by PHANTACi, Jay Chou and Ric’s fashion brand.',
        introduction_title4: 'Membership',
        introduction_content4: 'Your Phanta Bear doubles as your Fantasy membership card, and grants access to members-only benefits.',
        roadmap: 'ROADMAP',
        roadmap_time1: '2022',
        roadmap_time1_1: '01/01',
        roadmap_content1: 'Ezek.io platform and Phanta Bear NFT release and Ezek Club Community launch with special benefits',
        roadmap_time2: '2022',
        roadmap_time2_1: 'Q1',
        roadmap_content2: 'Community vote for 4 Phanta Bears from the digital NFT collection to be included in the physical upcoming Phantaci Spring 2022 collection. Another top celebrity NFT launch, Ezek Club online/offline benefits start to launch. Ezek virtual concert start to build.',
        roadmap_time3: '2022',
        roadmap_time3_1: 'Q2',
        roadmap_content3: 'Ezek Virtual Concert Launch. Buy a plot of virtual land and build a members-only clubhouse in the Metaverse. Collaborate with concerts and film studios. ',
        roadmap_time4: '2022',
        roadmap_time4_1: 'Q3',
        roadmap_content4: 'You will be able to use Ezek NFT to access to virtual concert.',
        matrix_banner_title: 'Matrix Labs is the technical partner of the Phanta Bear project',
        matrix_banner_content1: 'The Matrix Labs team is a group of experienced blockchain developers. They are partnering with Ezek and PHANTACi to bring the Phanta Bear NFT Collection to life on the blockchain.',
        matrix_banner_content2: 'Matrix Labs are also the creators behind Matrix World, an exciting next-generation metaverse project. In the Matrix World, users will be able to create, connect, explore, and play like never before; they will even be able to earn by selling their creations!',
        matrix_banner_content3: ' See more ',
        matrix_banner_content4: ' here',
        matrix_banner_content5: '.',
        team: 'TEAM',
        team_1: 'WILL L',
        team_2: 'Mark G',
        team_3: 'Ed Ow',
        collaborator: 'COLLABORATOR',
        outline: 'OUTLINE',
        faq: 'FAQ',
        more: 'MORE',
        links: 'LINKS',
        opensea: 'opensea'
    }
  };
