export default {
    zh: {
        your_account: '您的账户',
        wallet: '钱包',
        email: '邮箱',
        member_perk: '会员权益',
        member_perk_title1: '尊享特权',
        member_perk_content1: '通过购买 PHB，您将拥有 NFT 的商业权利，作为 NFT 持有人，您将从我们那里获得 10% 的商业特许权使用费，我们可能从您的 NFT 的商业用途中获得任何利润。',
        member_perk_title2: ' Fantasy俱乐部',
        member_perk_content2_1: '您的 Phanta Bear 兼作您的 Ezek 会员卡，并授予会员专享权益。例如：',
        member_perk_content2_2: '独享折扣',
        member_perk_content2_3: '抢先购买演唱会门票和免费后台通行证，让您结识喜爱的歌手和乐队。',
        member_perk_content2_4: '免费的电影首映门票和与演员见面的机会（音乐会和电影列表将在Discord频道中更新。）',
        member_perk_content2_5: '更多精彩会员权益即将到来……',
        member_perk_title3: '线下权益',
        member_perk_content3: 'PHANTACi生产的限量版Phanta Bear实物',
        member_perk_title4: '元宇宙',
        member_perk_content4: '您的Phanta Bear可以作为您的数字身份，让您访问元宇宙上的phantabear会所，以及 Ezek 平台未来主办/联合主办的 VR/XR 音乐会',
        member_perk_title5: 'the DAO',
        member_perk_content5: '我们将创建一个社区钱包，用于丰富 Phanta Bear 社区，所有 Phanta Bear 持有者都可以提出并投票旨在增加 Phanta Bear 价值的倡议，以及我们可能从商业用途中获得的任何利润的 10% Phanta Bear 将转到社区钱包。',
        member_perk_title6: '商店折扣',
        member_perk_content6: '全球 Phantaici 商店实体服装 15% 折扣'
    },
    en: {
        your_account: 'YOUR ACCOUNT',
        wallet: 'Wallet',
        email: 'Email',
        member_perk: 'PERKS OF OWNERSHIP',
        member_perk_title1: 'Royalities Cuts',
        member_perk_content1: 'By buying a PHB, you are granted the commercial rights to your NFT, and you as the NFT holder will get 10% commercial royalties on any profit we might generate from commercial use from your NFT in any future designs that we may use.',
        member_perk_title2: 'Fantasy Club',
        member_perk_content2_1: 'Your Phanta Bear doubles as your Fantasy membership card, and grants access to members-only benefits, such as:',
        member_perk_content2_2: 'Private discord',
        member_perk_content2_3: 'Early access to purchase the concert tickets and free backstage passes which allows you to meet you favourite singers and bands.',
        member_perk_content2_4: 'Free movie premiere tickets and chance for meet the actors/ actresses (Concerts and movies list will be updated in the members discord channel.)',
        member_perk_content2_5: 'And more exclusive membership benefits to come…',
        member_perk_title3: 'Physical Items',
        member_perk_content3: 'Limited edition of Phanta Bear physical items produced by PHANTACi.',
        member_perk_title4: 'Metaverse',
        member_perk_content4: 'Your Phanta Bear can serve as your digital identity and get you access to Phanta Bear Clubhouse on Metaverse, and future VR/XR concerts host/cohost by Ezek platform. ',
        member_perk_title5: 'The Dao',
        member_perk_content5: 'A community wallet will be created which will be used to enrich the Phanta Bear community. All Phanta Bear holders can propose and vote on initiatives meant to increase the value of the Phanta Bear, and 10% of any profit we might generate from commercial use from Phanta Bear will go to the community wallet.',
        member_perk_title6: 'Store Discounts ',
        member_perk_content6: '15% discount on physical clothing in Phantaici stores worldwide.'
    
    }
  };
