export default {
    zh: {
        your_account: '您的账户',
        wallet: '钱包',
        email: '邮箱',
        email_empty:'去绑定邮箱',
        member_perk: 'PHANTABEAR 会员权益',
        member_perk_title1: 'PhantaBear 俱乐部会员',
        member_perk_content1: 'PhantaBear NFT 是您于 PhantaBear 俱乐部身份凭证，成为 PhantaBear 持有者即可获得以下会员福利：',
        member_perk_title2: '',
        member_perk_content2_1: 'Discord 专属频道',
        member_perk_content2_2: 'Members-Only 专属线上商城',
        member_perk_content2_3: '线上、线下 Members-Only 专属聚会活动',
        member_perk_content2_4: '出示 NFT 享有 PHANTACi 门市会员专属折扣',
        member_perk_content2_5: '合作品牌的专属身份及福利',
        member_perk_content2_6: '和艺人明星互动的机会',
        member_perk_content2_7: '合作优质项目白名单抽奖权利',
        member_perk_title3: 'PhantaBear 实体产品',
        member_perk_content3: '持续产出赋予 PhantaBear 文化，由 PHANTACi 设计制造的 Members-Only 限量版实体产品。',
        member_perk_title4: 'PhantaBear 元宇宙',
        member_perk_content4: '进入PhantaBear 虚拟土地、游戏系列及虚拟演唱会独家权利。',
        member_perk_title5: 'Phanta Treature',
        member_perk_content5: '使用 PhantaBear 社区钱包。投票提案决定钱包的使用方向、建构社区，以及藉此扩展 PhantaBear 的全球影响力，最大化提升 PhantaBear 的价值。',
        member_perk_title6: '',
        member_perk_content6: ''
    },
    en: {
        your_account: 'YOUR ACCOUNT',
        wallet: 'Wallet',
        email: 'Email',
        email_empty:'Add your email',
        member_perk: 'PHANTABEAR Perks of Ownership',
        member_perk_title1: 'PhantaBear Club Member',
        member_perk_content1: 'PhantaBear NFT provides you with a membership identity in PHBC, access to more exclusive perks as blow:',
        member_perk_title2: '',
        member_perk_content2_1: 'Exclusive discord channel',
        member_perk_content2_2: 'Members-Only exclusive online store',
        member_perk_content2_3: 'Member-Only parties and exclusive activities (Online & Offline)',
        member_perk_content2_4: 'PHANTACi store Metaverse membership and exclusive discounts',
        member_perk_content2_5: 'Future partner brands‘ exclusive identities and perks',
        member_perk_content2_6: 'Opportunities to interact with established artists and celebrities',
        member_perk_content2_7: 'WL Raffle opportunities for select NFT projects',
        member_perk_title3: 'PhantaBear Physical Merchandise',
        member_perk_content3: 'PHNANTACi will design physical merchandise with limited editions to cultivate and show PhantaBear‘s unique culture',
        member_perk_title4: 'PhantaBear Metaverse',
        member_perk_content4: 'Members can enjoy exclusive access to Members-Only PhantaBear virtual lands, games, and virtual concerts',
        member_perk_title5: 'PhantaBear Treasure',
        member_perk_content5: '4.A community wallet that can be utilized by PhantaBear holders to expand PhantaBear‘s global influences in various fields. All holders can propose and vote on how to utilize the community wallet in order to maximize the value of PhantaBear',
        member_perk_title6: '',
        member_perk_content6: ''
    
    }
  };
