export default {
    zh: {
        your_account: '您的账户',
        wallet: '钱包',
        email: '邮箱',
        email_empty:'去绑定邮箱',
        member_perk: '会员权益',
        member_perk_title1: '尊享特权',
        member_perk_content1: '通过购买Phanta Bear，您将拥有 NFT 的商业权利，作为 NFT 持有人，您将从我们那里获得 10% 的商业特许权使用费，我们可能从您的 NFT 的商业用途中获得任何利润。',
        member_perk_title2: 'Ezek俱乐部',
        member_perk_content2_1: '您的 Phanta Bear 兼作您的 Ezek 会员卡，并授予会员专享权益。例如：',
        member_perk_content2_2: 'Ezek俱乐部独享折扣。',
        member_perk_content2_3: '抢先购买演唱会门票和免费后台通行证，让您结识一些您喜爱的歌手和乐队。',
        member_perk_content2_4: '免费的电影首映门票和与演员见面的机会（演唱会和电影列表将在Discord频道中更新）。',
        member_perk_content2_5: '更多精彩会员权益即将到来……',
        member_perk_title3: '线下权益',
        member_perk_content3: 'PHANTACi生产的限量版Phanta Bear实物。',
        member_perk_title4: '元宇宙',
        member_perk_content4: '您的Phanta Bear可以作为您的数字凭证，让您访问元宇宙上的 Phanta Bear Clubhouse，以及未来由 Ezek 主办/联合主办的 VR/XR 演唱会。',
        member_perk_title5: 'The Dao',
        member_perk_content5: '我们将创建一个社区钱包，用于丰富 Phanta Bear 社区，所有 Phanta Bear 持有者都可以提出并投票旨在增加 Phanta Bear 价值的倡议，以及我们可能从商业用途中获得的任何利润的 10% Phanta Bear 将转到社区钱包。',
        member_perk_title6: '商店折扣',
        member_perk_content6: 'Phanta Bear 的拥有者可以享受 PHANTACi 全球商店实体服装的 15% 折扣。'
    },
    en: {
        your_account: 'YOUR ACCOUNT',
        wallet: 'Wallet',
        email: 'Email',
        email_empty:'Add your email',
        member_perk: 'PERKS OF OWNERSHIP',
        member_perk_title1: 'Royalities Cuts',
        member_perk_content1: 'By owning a Phanta Bear, you are granted the commercial rights to your NFT, and as the NFT holder you will get 10% commercial royalties on any profit we generate from the commercial use of your NFT in any future designs.',
        member_perk_title2: 'Ezek Club',
        member_perk_content2_1: 'Your Phanta Bear doubles as your Ezek membership card, and grants access to members-only benefits, such as:',
        member_perk_content2_2: 'Ezek Club private Discord.',
        member_perk_content2_3: 'Early access to purchase the concert tickets and free backstage passes that allow you to meet some of your favourite bands and singers.',
        member_perk_content2_4: 'Free movie premiere tickets and a chance to meet the cast (The concert and movie list will be updated regularly in the members discord channel.)',
        member_perk_content2_5: 'And more exclusive membership benefits to come…',
        member_perk_title3: 'Physical Items',
        member_perk_content3: 'Limited edition of Phanta Bear physical items produced by PHANTACi.',
        member_perk_title4: 'Metaverse',
        member_perk_content4: 'Your Phanta Bear can serve as your digital identity and gets you access to Phanta Bear Clubhouse in the Metaverse as well as future VR/XR concerts hosted/co-hosted by Ezek Club.',
        member_perk_title5: 'The Dao',
        member_perk_content5: 'A community wallet will be created which will be used to enrich the Phanta Bear community. All Phanta Bear holders can propose and vote on initiatives meant to increase the value of Phanta Bear. 10% of any profit we generate from the commercial use of Phanta Bears will go to the community wallet.',
        member_perk_title6: 'Store Discounts ',
        member_perk_content6: 'Phanta Bear owners get a 15% discount on physical clothing in PHANTACi stores worldwide.'
    
    }
  };
